SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, EP.FIRST_NAME AS MANAGER_NAME, EP.LAST_NAME AS MANAGER_LASTNAME
FROM EMPLOYEES E, EMPLOYEES EP
WHERE E.MANAGER_ID = EP.MANAGER_ID;

// Solution to the problem with join statement;

SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, EP.FIRST_NAME AS MANAGER_NAME, EP.LAST_NAME AS MANAGER_LASTNAME
FROM EMPLOYEES E JOIN EMPLOYEES EP
ON E.MANAGER_ID = EP.MANAGER_ID;