SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, E.COMMISSION_PCT, L.CITY, J.JOB_TITLE
FROM EMPLOYEES E,DEPARTMENTS D,LOCATIONS L, JOBS J
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND D.LOCATION_ID = L.LOCATION_ID
AND E.JOB_ID = J.JOB_ID
AND E.COMMISSION_PCT IS NULL 
AND J.JOB_TITLE='Programmer';

// Solution to the problem with join statement;

SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, E.COMMISSION_PCT, L.CITY, J.JOB_TITLE
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
AND E.COMMISSION_PCT IS NULL
AND J.JOB_TITLE = 'Programmer';