SELECT E.FIRST_NAME|| ' ' ||E.LAST_NAME|| ' ' ||B.FIRST_NAME|| ' ' ||B.LAST_NAME 
    as SAME_NAME_DIFFERENT_LASTNAME
FROM EMPLOYEES E, EMPLOYEES B  
WHERE E.FIRST_NAME = B.FIRST_NAME  
AND E.LAST_NAME <> B.LAST_NAME;