SELECT E.FIRST_NAME|| ' ' ||E.LAST_NAME|| ' ' ||B.FIRST_NAME|| ' ' ||B.LAST_NAME 
    as AYNI_İSİM_FARKLI_SOYAD
FROM EMPLOYEES E, EMPLOYEES B  
WHERE E.FIRST_NAME = B.FIRST_NAME  
AND E.LAST_NAME <> B.LAST_NAME;