SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, D.DEPARTMENT_NAME  
FROM EMPLOYEES E, DEPARTMENTS D  
WHERE (D.DEPARTMENT_ID, E.SALARY) = ANY (  
    SELECT E.DEPARTMENT_ID, MIN(SALARY)  
    FROM EMPLOYEES E  
    GROUP BY E.DEPARTMENT_ID  
);