SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY  
FROM EMPLOYEES E, DEPARTMENTS D  
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID  
AND E.DEPARTMENT_ID = 30  
AND E.SALARY <= (SELECT AVG(E.SALARY) FROM EMPLOYEES E);