SELECT E.FIRST_NAME, E.LAST_NAME, E.HIRE_DATE, J.JOB_TITLE  
FROM EMPLOYEES E, JOBS J  
WHERE E.JOB_ID = J.JOB_ID  
AND E.HIRE_DATE = (  
    SELECT MAX(E.HIRE_DATE)  
    FROM EMPLOYEES E  
    WHERE E.JOB_ID = ANY (  
        SELECT J.JOB_ID  
        FROM JOBS J  
        WHERE J.JOB_TITLE LIKE '%Clerk'  
    )
);