SELECT MAX(SALARY) AS "EN ÇOK",  
       MIN(SALARY) AS "EN AZ",  
       SUM(SALARY) AS "TOPLAM",  
       (MAX(SALARY) + MIN(SALARY)) / 2 AS "MAX-MIN-AVG",  
       ROUND(AVG(SALARY), 1) AS "ORTALAMA"  
FROM EMPLOYEES;