SELECT E.DEPARTMENT_ID, D.DEPARTMENT_NAME,  
       ROUND(MAX(SALARY), 2) AS MAX_SALARY,  
       ROUND(AVG(SALARY), 2) AS AVERAGE_SALARY  
FROM EMPLOYEES E, DEPARTMENTS D  
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID  
GROUP BY E.DEPARTMENT_ID, D.DEPARTMENT_NAME;