SELECT E.DEPARTMENT_ID, D.DEPARTMENT_NAME,  
       ROUND(MAX(SALARY), 2) AS EN_YUKSEK_MAAS,  
       ROUND(AVG(SALARY), 2) AS ORTALAMA_MAAS  
FROM EMPLOYEES E, DEPARTMENTS D  
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID  
GROUP BY E.DEPARTMENT_ID, D.DEPARTMENT_NAME;