SELECT D.DEPARTMENT_NAME
FROM DEPARTMENTS D
WHERE D.DEPARTMENT_ID IN (
  SELECT E.DEPARTMENT_ID
  FROM EMPLOYEES E
  GROUP BY E.DEPARTMENT_ID
  HAVING AVG(E.SALARY) > (SELECT AVG(SALARY) FROM EMPLOYEES)
);

//Sorunun Join ifadesi ile çözümü;

SELECT D.DEPARTMENT_NAME
FROM DEPARTMENTS D
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
HAVING AVG(E.SALARY) > (SELECT AVG(SALARY) FROM EMPLOYEES);