SELECT J.JOB_TITLE, 
       COUNT(*) AS NUMBER_OF_EMPLOYEES, 
       SUM(E.SALARY) AS TOTAL_SALARY, 
       ROUND(AVG(E.SALARY), 2) AS AVERAGE_SALARY
FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_TITLE
HAVING COUNT(*) > 3;

// Solution to the problem with join statement;

SELECT J.JOB_TITLE, 
       COUNT(E.EMPLOYEE_ID) AS NUMBER_OF_EMPLOYEES, 
       SUM(E.SALARY) AS TOTAL_SALARY, 
       ROUND(AVG(E.SALARY), 2) AS AVERAGE_SALARY
FROM EMPLOYEES E
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_TITLE
HAVING COUNT(E.EMPLOYEE_ID) > 3;