SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, J.JOB_TITLE FROM EMPLOYEES E, JOBS J
WHERE J.JOB_TITLE = 'Programmer'
AND E.JOB_ID = J.JOB_ID;

// Sorunun Join ifadesi ile çözümü;

SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, J.JOB_TITLE 
FROM EMPLOYEES E JOIN JOBS J
ON E.JOB_ID = J.JOB_ID
AND J.JOB_TITLE = 'Programmer';