SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, EP.FIRST_NAME AS MÜDÜR_ADI, EP.LAST_NAME AS MÜDÜR_SOYAD
FROM EMPLOYEES E, EMPLOYEES EP
WHERE E.MANAGER_ID = EP.MANAGER_ID;

// Sorunun Join ifadesi ile çözümü;

SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, EP.FIRST_NAME AS MÜDÜR_ADI, EP.LAST_NAME AS MÜDÜR_SOYAD 
FROM EMPLOYEES E JOIN EMPLOYEES EP
ON E.MANAGER_ID = EP.MANAGER_ID;