SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, E.HIRE_DATE, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE to_char(sysdate,'yyyy')-to_char(E.HIRE_DATE,'yyyy')>15
AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND D.DEPARTMENT_NAME = 'Marketing';

// Sorunun Join ifadesi ile çözümü;

SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, E.HIRE_DATE, D.DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND to_char(sysdate,'yyyy')-to_char(E.HIRE_DATE,'yyyy')>15
AND D.DEPARTMENT_NAME = 'Marketing';