SELECT J.JOB_TITLE, COUNT(E.EMPLOYEE_ID)  
FROM JOBS J, EMPLOYEES E  
WHERE E.JOB_ID = J.JOB_ID  
GROUP BY E.JOB_ID, J.JOB_TITLE  
HAVING COUNT(E.EMPLOYEE_ID) = (  
    SELECT MAX(COUNT(*))  
    FROM EMPLOYEES E  
    GROUP BY E.JOB_ID
);