SELECT SUBSTR(E.FIRST_NAME, 1, 1)  as ENÇOK_GEÇEN_HARF
FROM EMPLOYEES E  
GROUP BY SUBSTR(E.FIRST_NAME, 1, 1)  
HAVING COUNT(*) = (  
    SELECT MAX(COUNT(*))  
    FROM EMPLOYEES E  
    GROUP BY SUBSTR(E.FIRST_NAME, 1, 1)
);