SELECT C.COUNTRY_NAME, COUNT(C.COUNTRY_NAME)  
FROM COUNTRIES C, LOCATIONS L  
WHERE C.COUNTRY_ID = L.COUNTRY_ID  
GROUP BY C.COUNTRY_NAME  
HAVING COUNT(C.COUNTRY_NAME) = (  
    SELECT MIN(COUNT(*))  
    FROM LOCATIONS L  
    GROUP BY L.CITY
);