SELECT J.JOB_TITLE, 
       COUNT(*) AS CALISAN_SAYISI, 
       SUM(E.SALARY) AS TOPLAM_MAAS, 
       ROUND(AVG(E.SALARY), 2) AS ORTALAMA_MAAS
FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_TITLE
HAVING COUNT(*) > 3;

//Sorunun Join ifadesi ile çözümü;

SELECT J.JOB_TITLE, 
       COUNT(E.EMPLOYEE_ID) AS CALISAN_SAYISI, 
       SUM(E.SALARY) AS TOPLAM_MAAS, 
       ROUND(AVG(E.SALARY), 2) AS ORTALAMA_MAAS
FROM EMPLOYEES E
JOIN JOBS J ON E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_TITLE
HAVING COUNT(E.EMPLOYEE_ID) > 3;